version: '3.8'

services:
    postgres:
        image: postgres:15-alpine
        container_name: high_concurrency_db
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: supersecretpassword
            POSTGRES_DB: ticket_db
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        container_name: high_concurrency_cache
        ports:
            - "6379:6379"

volumes:
    pgdata:
